biome-distribution:
  # Biome distribution refers to the placement of biomes, this does *NOT*
  # include aspects like terrain height / shape within biomes, or anything
  # else that generates within any given biome.
  
  # These parameters are designed to allow for easy modification of biome distribution,
  # and are injected into the various biome distribution configs via meta-configuration.
  # You can find these configs in the biome-providers directory, most of which contain
  # additional more specific parameters. 



  # Dragon Island Configuration
  # Controls various features of the dragon island

  dragon-pit-radius: 0
  # Adds a pit around the dragon fountain that is now on a small floating center island. Disabled by default at 0. 
  # Enable the dragon pit by setting the radius to the recommended 28 or any other digit.

  dragon-chains-toggle: 0
  # Adds giant obsidian chains at the corners of the dragon island. Disabled by default at 0. 
  # Enable the dragon island chains by setting the value to 1.

  main-end-scale: 150
  # Controls general size of the main end island.  Larger scale = larger main end island.
  # Default: 150
  
  void-buffer-scale: 1000
  # Controls size of void "buffer" zone between main and outer end areas.  Larger scale = larger main end island.
  # Default: 1000

  small-pillar-radius: 80
  # Controls the radius of small pillars at the main end island from the center of the island
  # Default: 80



  # Rings of Life Distribution
  # Each controls the width and biome scale of each ring starting from the center

  ring1-width: 1000
  # Default: 1000
  ring1-biome-scale: 500
  # Default: 500

  ring2-width: 1000
  # Default: 1000
  ring2-biome-scale: 1000
  # Default: 1000

  ring3-width: 1000
  # Default: 1000
  ring3-biome-scale: 1000
  # Default: 1000

  ring4-width: 1000
  # Default: 1000
  ring4-biome-scale: 500
  # Default: 500

  ring5-biome-scale: 500
  # Default: 500
  ring5-width: 1000
  # Default: 1000

  frontier-biome-scale: 1000
  # Default: 1000



  # Void Distribution
  # Controls the distribution of void biomes

  void-scale: 1500
  # Controls the scale of void biomes.
  # Default: 1500
  
  void-biome-scale: 1000
  # Controls the scale of void biomes.
  # Default: 1000



  # Aether Distribution
  # Controls the distribution of Aether biomes

  aether-biome-scale: 1000
  # Controls the scale of aether biomes within regions. 
  # Default: 1000

  aether-region-scale: 1000
  # Controls the scale of aether regions. 
  # Default: 1000

  aether-cloud-sea-scale: 500
  # Controls the scale of cloud sea zones. 
  # Default: 500

  aether-ancient-scale: 1000
  # Controls the scale of ancient aether zones. 
  # Default: 1000



  global-scale: 1
  # Modifies the scale of everything, you can use this parameter to if you
  # want just about every biome to be larger or smaller.
  # By doubling the scale, you double the length & width of everything,
  # e.g. if you have a biome that is 300 blocks wide with a scale of 1, and
  # increase that scale to 2, that biome will generate 600 blocks wide.
  # Default: 1

terrain-configuration:

  # Controls the terrain generation of default end terrain (Effects vary across biomes)

  island-scale: 1
  # Scale of default terrain
  # Default: 1

  island-threshold: 0.3
  # Threshold or density of default island
  # Default: 0.3

  island-max-height: 250
  # Max height of default terrain
  # Default: 250

  island-min-height: -40
  # Lowest height of default terrain
  # Default: -40

  island-taper: 100
  # Range for narrowing deafault terrain
  # Default: 100

  island-flatness: 5
  # Flatness of default terrain
  # Default: 5

  island-undercarriage-translate: -10
  # Translate placement of default terrain undercarriage
  # Default: -10
