biome-distribution:
  # Biome distribution refers to the placement of biomes, this does *NOT*
  # include aspects like terrain height / shape within biomes, or anything
  # else that generates within any given biome.

  # These parameters are designed to allow for easy modification of biome distribution,
  # and are injected into the various biome distribution configs via meta-configuration.
  # You can find these configs in the biome-providers directory, most of which contain
  # additional more specific parameters.

  main-end-scale: 150
  # Controls general size of the main end island.  Larger scale = larger main end island.
  # Default: 150

  void-buffer-scale: 1000
  # Controls size of void "buffer" zone between main and outer end areas.  Larger scale = larger main end island.
  # Default: 1000

  # ---
  # Rings of Life Distribution
  # Each controls the width and biome scale of each ring starting from the center
  # ---

  ring1-width: 1000
  ring2-width: 1000
  ring3-width: 1000
  ring4-width: 1000
  ring5-width: 1000
  # Width of each individual ring
  # Default: 1000

  ring1-biome-scale: 1000
  ring2-biome-scale: 1000
  ring3-biome-scale: 1000
  ring4-biome-scale: 1000
  ring5-biome-scale: 1000
  # Scale of biomes within each individual ring
  # Default: 1000

  frontier-biome-scale: 1000
  # Scale of end biomes in the outer end frontier after ring distribution
  # Default: 1000

  # ---
  # Void Distribution
  # Controls the distribution of void biomes
  # ---

  void-scale: 1500
  # Controls the scale of void biomes.
  # Default: 1500

  void-biome-scale: 1000
  # Controls the scale of void biomes.
  # Default: 1000

  # ---
  # Aether Distribution
  # Controls the distribution of aether biomes
  # ---

  aether-biome-scale: 1000
  # Controls the scale of aether biomes within regions.
  # Default: 1000

  aether-region-scale: 1000
  # Controls the scale of aether regions.
  # Default: 1000

  aether-cloud-sea-scale: 200
  # Controls the scale of cloud sea zones.
  # Default: 200

  aether-ancient-scale: 1000
  # Controls the scale of ancient aether zones.
  # Default: 1000

  # ---

  global-scale: 1
  # Modifies the scale of everything, you can use this parameter to if you
  # want just about every biome to be larger or smaller.
  # By doubling the scale, you double the length & width of everything,
  # e.g. if you have a biome that is 300 blocks wide with a scale of 1, and
  # increase that scale to 2, that biome will generate 600 blocks wide.
  # Default: 1

terrain-configuration:

  # ---
  # End Terrain Configuration
  # Controls the terrain generation of default end terrain (Effects vary across biomes)
  # ---

  island-scale: 1
  # Scale of default terrain
  # Default: 1

  island-threshold: 0.4
  # Threshold or density of default island
  # Default: 0.4

  island-max-height: ${meta.yml:top-y} - 20
  # Max height of default terrain
  # Default: ${meta.yml:top-y} - 20

  island-min-height: ${meta.yml:bottom-y} + 20
  # Lowest height of default terrain
  # Default: ${meta.yml:bottom-y} + 20

  island-taper: 100
  # Range for narrowing default terrain
  # Default: 100

  island-flatness: 5
  # Flatness of default terrain
  # Default: 5

  island-undercarriage-translate: -10
  # Translate placement of default terrain undercarriage
  # Default: -10

  # ---
  # Aether Terrain Configuration
  # Controls the terrain generation of default aether terrain (Effects vary across biomes)
  # ---

  aether-island-scale: 1
  # Scale of default terrain
  # Default: 1

  aether-island-threshold: 0.4
  # Threshold or density of default island
  # Default: 0.4

  aether-island-max-height: ${meta.yml:top-y} - 20
  # Max height of default terrain
  # Default: ${meta.yml:top-y} - 20

  aether-island-min-height: ${meta.yml:bottom-y} + 20
  # Lowest height of default terrain
  # Default: ${meta.yml:bottom-y} + 20

  aether-island-taper: 100
  # Range for narrowing default terrain
  # Default: 100

  aether-island-flatness: 5
  # Flatness of default terrain
  # Default: 5

  aether-island-undercarriage-translate: -10
  # Translate placement of default terrain undercarriage
  # Default: -10

# World Y levels
top-y: 319
# Default: 319

bottom-y: 0
# Default: 0

