end-plantable-blocks:
  - minecraft:yellow_concrete_powder
  - minecraft:light_blue_concrete_powder
  - minecraft:cyan_concrete_powder
  - minecraft:magenta_concrete_powder
  - minecraft:purple_concrete_powder
  - minecraft:black_concrete_powder
  - minecraft:white_concrete_powder
  - minecraft:lime_concrete_powder
  - minecraft:green_concrete_powder
  - minecraft:pink_concrete_powder
  - minecraft:red_concrete_powder
  - minecraft:blue_concrete_powder
  - minecraft:orange_concrete_powder
  - minecraft:dead_tube_coral_block
  - minecraft:dead_brain_coral_block
  - minecraft:dead_bubble_coral_block
  - minecraft:dead_fire_coral_block
  - minecraft:dead_horn_coral_block
  - minecraft:purple_terracotta
  - minecraft:blue_terracotta

plantable-blocks:
  - minecraft:mud
  - minecraft:grass_block
  - minecraft:podzol
  - minecraft:dirt
  - minecraft:coarse_dirt
  - minecraft:moss_block
  - minecraft:rooted_dirt

structure-blocks:
  - minecraft:end_stone_bricks
  - minecraft:magenta_stained_glass
  - minecraft:purpur_stairs
  - minecraft:purpur_slab
  - minecraft:purpur_pillar
  - minecraft:purpur_block
  - minecraft:smooth_quartz
