stages:
  - type: REPLACE
    sampler: 
      dimensions: 2
      type: FBM
      octaves: 2
      sampler:
        type: OPEN_SIMPLEX_2
        salt: 6836
        frequency: 1 / ${meta.yml:biome-distribution.aether-biome-scale} / ${meta.yml:biome-distribution.global-scale}
    from: aether
    to:
      - AETHER_CLOUD_SEA: 1
      - aether-coasts: 1
      - aether-lowlands: 2
      - aether-midlands: 2
      - aether-highlands: 1

  - type: REPLACE_LIST
    sampler: 
      dimensions: 2
      type: FBM
      octaves: 2
      sampler:
        type: OPEN_SIMPLEX_2
        salt: 6836
        frequency: 1 / ${meta.yml:biome-distribution.aether-biome-scale} / ${meta.yml:biome-distribution.global-scale}
    default-from: aether-coasts
    default-to:
      - AETHER_INSIPID_COASTS: 1
    to: 
      aether-lowlands:
      - AETHER_AZURE_MEADOWS: 1
      - AETHER_AUREATE_FOREST: 1
      - AETHER_LAVENDER_DRIFTLANDS: 1

      aether-midlands:
      - AETHER_BRAMBLE_WILDS: 2
      - AETHER_FLOATING_CLIFFS: 1

      aether-highlands:
      - AETHER_CRIMSON_HEIGHTS: 1
      
  