stages:
  - type: REPLACE
    sampler: 
      dimensions: 2
      type: FBM
      octaves: 2
      sampler:
        type: CELLULAR
        return: CellValue
        salt: 6836
        frequency: 1 / ${meta.yml:biome-distribution.aether-region-scale} / ${meta.yml:biome-distribution.global-scale}
    from: aether
    to:
      - AETHER_CLOUD_SEA: 1
      - aether-coasts: 2
      - aether-lowlands: 3
      - aether-midlands: 3
      - aether-highlands: 2
      - aether-mountains: 1

  - type: REPLACE_LIST
    sampler: 
      dimensions: 2
      type: FBM
      octaves: 2
      sampler:
        type: CELLULAR
        return: CellValue
        salt: 4567
        frequency: 1 / ${meta.yml:biome-distribution.aether-biome-scale} / ${meta.yml:biome-distribution.global-scale}
    default-from: aether-coasts
    default-to:
      - AETHER_INSIPID_COASTS: 1
      - AETHER_MARBLE_COASTS: 1
    to: 
      aether-lowlands:
      - AETHER_AZURE_MEADOWS: 1
      - AETHER_TENEBROUS_THICKET: 1
      - AETHER_DRIFTFALLS: 1
      - AETHER_CRIMSIC_LANDSCAPES: 1

      aether-midlands:
      - AETHER_FROSTBITE_WOODS: 1
      - AETHER_BRAMBLE_WILDS: 1
      - AETHER_GOLDEN_FIELDS: 1

      aether-highlands:
      - AETHER_HONEY_HEIGHTS: 1
      - AETHER_ORCHARD_WOODLANDS: 1
      
      aether-mountains:
      - AETHER_FRIGID_CLIFFS: 1
      - AETHER_PRISMATIC_RIDGES: 1
      
  