distribution-map: &distribution-map
  dimensions: 2
  type: FBM
  octaves: 2
  sampler:
    type: OPEN_SIMPLEX_2
    salt: 6836
    frequency: 1 / ${meta.yml:biome-distribution.aether-biome-scale} / ${meta.yml:biome-distribution.global-scale}

stages:
  - type: REPLACE_LIST
    sampler: *distribution-map
    default-from: aether
    default-to:
      - AETHER_PLAINS: 1
      - AETHER_BUMPY: 1
      - AETHER_FOREST: 1
      - AETHER_LUSH_FOREST: 1
      - AETHER_AZURE_MEADOWS: 1
      - AETHER_AUREATE_FOREST: 1
      - AETHER_DRIFTLANDS: 1
      - AETHER_LAVENDER_DRIFTLANDS: 1
      - AETHER_CRIMSON_HEIGHTS: 1
    #  - AETHER_GLIDED_DESERT: 1
      - AETHER_GRIM_WOODLANDS: 1
      - AETHER_REDWOOD_FOREST: 1
      - AETHER_DISCUS_AETHER: 1
      - AETHER_CLOUDLANDS: 1
      - AETHER_TAINTED: 1
    to: 
      aether_highlands:
      - AETHER_HIGHLANDS: 1
      - AETHER_HIGHLANDS_FOREST: 1
      - AETHER_FLOATING_CLIFFS: 1
      - AETHER_BRISTLED_FOREST: 1
      - AETHER_ANCIENT_WASTES: 1
      - AETHER_FROSTY_WOODS: 1
      - AETHER_RUGGED_CLIFFS: 1
  