distribution-map: &distribution-map
  dimensions: 2
  type: FBM
  octaves: 2
  sampler:
    type: OPEN_SIMPLEX_2
    salt: 6836
    frequency: 1 / ${meta.yml:biome-distribution.end-biome-scale} / ${meta.yml:biome-distribution.end-scale} / ${meta.yml:biome-distribution.global-scale}

stages:
  - type: REPLACE_LIST
    sampler: *distribution-map
    default-from: end
    default-to:
      - END_WASTES: 1
      - END_HIGHLANDS: 1
      - TRIGONAL_END: 1
      - WARPED_BARRENS: 1
      - WARPED_FOREST: 1
      - WARPED_GROVE: 1
      - CHORUVE_FOREST: 1
      - MAUVE_FOREST: 1
      - CRAGGY_END: 1
      - FLAXEN_FOREST: 1
      - DARK_END: 1
      - AMETHYST_END: 1
      - TAINTED_END: 1
      - CRYING_END: 1
      - CORRUPTED_END: 1
      - PEARLESCENT_END: 1
    to: 
      shattered_end:
        - SHATTERED_END: 4
        - SHATTERED_FOREST: 2
        - JAGGED_END: 1
      void:
        - VOID: 4
        - STARFIELD: 2
        - ASTEROID_FIELD: 1