distribution-map: &distribution-map
  type: EXPRESSION
  expression: split((noise(x/spread,z/spread)+1)*4/(radius/spread)-1)
  variables:
    spread: 1500
    radius: 350
  functions:
    split:
      arguments: [x]
      expression: if(x<1,x,1)
  samplers:
    noise:
      dimensions: 2
      type: DOMAIN_WARP
      amplitude: 0.01
      warp:
        type: OPEN_SIMPLEX_2
        salt: 3912
        frequency: 10
      sampler:
        type: CELLULAR
        salt: 5912
        frequency: 1
        return: Distance2Div

stages:
  - type: REPLACE
    sampler: *distribution-map
    from: outer_end
    to:
      - aether: 24
      - STARFIELD: 32
      - end: 64
  - type: REPLACE_LIST
    sampler:
      dimensions: 2
      type: FBM
      octaves: 2
      sampler:
        type: OPEN_SIMPLEX_2
        salt: 1196
        frequency: 1 / ${meta.yml:biome-distribution.end-scale} / ${meta.yml:biome-distribution.global-scale}
    default-from: end
    default-to:
      - void: 1
      - end: 2
    to:
      aether:
        - aether: 2
        - aether_highlands: 1