distribution-map: &distribution-map
  dimensions: 2
  type: FBM
  octaves: 2
  sampler:
    type: OPEN_SIMPLEX_2
    salt: 1196
    frequency: 1 / ${meta.yml:biome-distribution.void-biome-scale} / ${meta.yml:biome-distribution.global-scale}

stages:
  - type: REPLACE_LIST
    sampler: *distribution-map
    default-from: ring1
    default-to:
      - VOID: 1
      - ring1: 3
    to:
      ring2:  
        - void: 1
        - ring2: 3
      ring3:  
        - void: 1
        - ring3: 3
      ring4:  
        - void: 1
        - ring4: 3
      ring5:  
        - void: 1
        - ring5: 3
  - type: REPLACE
    sampler: *distribution-map
    from: void
    to:
      - VOID: 4
      - STARFIELD: 1
      - GALAXY_FIELD: 1
      - ASTEROID_FIELD: 1   